
This journey begins one late Monday afternoon in Antwerp.
Our team desperately needs coffee, but none of us dare open the office door.

To leave means code dismemberment and certain death.


Rubies are red, +
Topazes are blue.



[%hardbreaks]
Ruby is red.
Java is black.


= Line Break Doc Title
:hardbreaks:

Rubies are red,
Topazes are blue


WARNING: Wolpertingers are known to nest in server racks.
Enter at your own risk.

CAUTION: Wolpertingers are known to nest in server racks.
Enter at your own risk.

I can't believe it, we *won*!


---

bold *constrained* & **un**constrained

italic _constrained_ & __un__constrained

bold italic *_constrained_* & **__un__**constrained

monospace `constrained` & ``un``constrained

monospace bold `*constrained*` & ``**un**``constrained

monospace italic `_constrained_` & ``__un__``constrained

monospace bold italic `*_constrained_*` & ``**__un__**``constrained


Type the word [.userinput]#asciidoc# into the search bar.

<span class="userinput">asciidoc</span>